current:
	g++ -std=c++11 TestKVMultithreaded.cpp -o TestKVMultithreaded.o -lkvstore -lboost_serialization -Wno-deprecated

all:
	g++ -std=c++11 TestKVSingleRead.cpp -o TestKVSingleRead.o -lkvstore -lboost_serialization -Wno-deprecated

clean:
	rm *.o
